Add functionality to use different OCP versions

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -28,14 +28,40 @@ inputs:
     description: 'Wait for all operators to be ready'
     required: false
     default: 'false'
+  desiredOCPVersion:
+    description: 'OpenShift version to deploy'
+    required: false
+    default: 'latest'
 
 runs:
   using: 'composite'
   steps:
+
+    - name: Set CRC version variable
+      id: set_crc_version
+      shell: bash
+      run: |
+        if [ "${{ inputs.desiredOCPVersion }}" = "latest" ]; then
+          echo "crc_version=latest" | tee "$GITHUB_OUTPUT"
+        else
+          if [ "${{ inputs.desiredOCPVersion }}" = "4.15" ]; then
+            echo "[ERROR] OpenShift version 4.15 is not supported in this action due to known compatibility issues with modern runners." >&2
+            exit 1
+          fi
+          CRC_VERSION=$("${{ github.action_path }}/scripts/fetch-ocp-crc-version.sh" "${{ inputs.desiredOCPVersion }}")
+          if [[ $CRC_VERSION == No* ]]; then
+            echo "[ERROR] The requested OpenShift version (${{ inputs.desiredOCPVersion }}) is not supported or no matching CRC release was found." >&2
+            echo "Details: $CRC_VERSION" >&2
+            echo "Please choose a supported OCP version (e.g., 4.10 or above, except 4.15) or check https://github.com/crc-org/crc/releases for available versions." >&2
+            exit 1
+          fi
+          echo "crc_version=$CRC_VERSION" | tee "$GITHUB_OUTPUT"
+        fi
+
     - name: Download and Install OpenShift Local Binary
       shell: bash
       run: |
-        curl -L -o crc.tar.xz https://mirror.openshift.com/pub/openshift-v4/clients/crc/latest/crc-linux-amd64.tar.xz
+        curl -L -o crc.tar.xz "https://mirror.openshift.com/pub/openshift-v4/clients/crc/${{ steps.set_crc_version.outputs.crc_version }}/crc-linux-amd64.tar.xz"
         tar -xvf crc.tar.xz
         sudo mv crc-linux-*/crc /usr/local/bin
 
